export const addProductFormData = {
    namePD: '',
    codePD: '',
    select: '',
    category: '',
    price: '',
    origin: '',
    capacity: '',
    describe: '',
    fragrance: '',
    style: '',
    image: null,
  };
  
  export const productDetailFormData = {
    nameProducts: '',
    codeProducts: '',
    description: '',
    origin: '',
    capacity: 0,
    quantity: 0,
    fragranceGroup: '',
    style: '',
    price: 0,
    priceSale: 0,
    isHome: false,
    isSale: false,
    isFeature: false,
    isHot: false,
    category: '',
    branch: '',
    createBy: '',
    createDate: '',
  };